# Config file for automatic testing at travis-ci.org
sudo: true 
branches:
  only:
    - master
    - test
language: python
python:
  - 3.6
services:
  - postgresql
install: 
  - pip install -r requirements.txt
  # - apt-get install postgresql
  # - sudo -u postgres createuser -s -P -e $USER
  # - createdb ether_sql
  # - psql ether_sql < tests/ether_sql_test.sql
before_script:
  - psql -c 'create database ether_sql;' -U postgres
  - psql -c "CREATE USER root WITH PASSWORD 'develop';" -U postgres
  - psql ether_sql < tests/ether_sql_test.sql
  - export FLASK_APP="api/api.py"
  - export FLASK_DEBUG=1

script: echo "Build Done"

after_script:
  - flask run & APP_PID=$!
  - curl -i http://127.0.0.1:5000/v1.0/current_blockNumber/