# Config file for automatic testing at travis-ci.org
sudo: true 
branches:
  only:
    - master
    - test
language: python
python:
  - 3.6
services:
  - postgresql
install: 
  - pip install -r requirements.txt
before_script:
  - psql -c 'create database ether_sql;' -U postgres
  - psql -c "CREATE USER root WITH PASSWORD 'develop';" -U postgres
  - psql ether_sql < tests/ether_sql_test.sql
  - export FLASK_APP="api/api.py"
  - export FLASK_DEBUG=1

script: echo "Build Done"

after_script:
  - |
    python api/api.py &
    APP_PID=$!
  - curl -s https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip > ngrok.zip
  - unzip ngrok.zip
  - ./ngrok http 5000 > /dev/null &

  # sleep to allow ngrok to initialize
  - sleep 2

  # extract the ngrok url
  - NGROK_URL=$(curl -s localhost:4040/api/tunnels/command_line | jq --raw-output .public_url)
  - curl -i $NGROK_URL/v1.0/current_blockNumber/
  - kill $APP_PID